# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_welcomeDialog(object):
    def setupUi(self, welcomeDialog):
        welcomeDialog.setObjectName("welcomeDialog")
        welcomeDialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(welcomeDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(240, 150, 151, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.enterButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enterButton.setMinimumSize(QtCore.QSize(0, 40))
        self.enterButton.setObjectName("enterButton")
        self.verticalLayout.addWidget(self.enterButton)
        self.exitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.exitButton.setMinimumSize(QtCore.QSize(0, 40))
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(welcomeDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 221, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 30, 0, 30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.title.setObjectName("title")
        self.verticalLayout_2.addWidget(self.title)
        self.credit = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.credit.sizePolicy().hasHeightForWidth())
        self.credit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("STHeiti")
        self.credit.setFont(font)
        self.credit.setAlignment(QtCore.Qt.AlignCenter)
        self.credit.setObjectName("credit")
        self.verticalLayout_2.addWidget(self.credit)
        self.credit2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.credit2.sizePolicy().hasHeightForWidth())
        self.credit2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.credit2.setFont(font)
        self.credit2.setAlignment(QtCore.Qt.AlignCenter)
        self.credit2.setObjectName("credit2")
        self.verticalLayout_2.addWidget(self.credit2)

        self.retranslateUi(welcomeDialog)
        QtCore.QMetaObject.connectSlotsByName(welcomeDialog)

    def retranslateUi(self, welcomeDialog):
        _translate = QtCore.QCoreApplication.translate
        welcomeDialog.setWindowTitle(_translate("welcomeDialog", "SkiInfo - Welcome!"))
        self.enterButton.setText(_translate("welcomeDialog", "进入应用"))
        self.exitButton.setText(_translate("welcomeDialog", "退出"))
        self.title.setText(_translate("welcomeDialog", "SKIINFO"))
        self.credit.setText(_translate("welcomeDialog", "作者：张辰芃@北京大学"))
        self.credit2.setText(_translate("welcomeDialog", "Based on QGIS3.12-LTR"))
